// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOZW8aUamMNEEsOhqhO1U8Q5Yq3EtvToo',
    appId: '1:955529046615:web:40ea4f5a97bb44c9329112',
    messagingSenderId: '955529046615',
    projectId: 'chatap-e0e73',
    authDomain: 'chatap-e0e73.firebaseapp.com',
    storageBucket: 'chatap-e0e73.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoUMVoADBeC0C6hfgHps0QTZNAKZwFZ1Y',
    appId: '1:955529046615:android:df73470e96cebcf0329112',
    messagingSenderId: '955529046615',
    projectId: 'chatap-e0e73',
    storageBucket: 'chatap-e0e73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH3zBH_uczgMAtz1MPN8pSo1fztFUNAXU',
    appId: '1:955529046615:ios:cd462a0fb1e1a650329112',
    messagingSenderId: '955529046615',
    projectId: 'chatap-e0e73',
    storageBucket: 'chatap-e0e73.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH3zBH_uczgMAtz1MPN8pSo1fztFUNAXU',
    appId: '1:955529046615:ios:cd462a0fb1e1a650329112',
    messagingSenderId: '955529046615',
    projectId: 'chatap-e0e73',
    storageBucket: 'chatap-e0e73.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOZW8aUamMNEEsOhqhO1U8Q5Yq3EtvToo',
    appId: '1:955529046615:web:da7aad3b3a5887c5329112',
    messagingSenderId: '955529046615',
    projectId: 'chatap-e0e73',
    authDomain: 'chatap-e0e73.firebaseapp.com',
    storageBucket: 'chatap-e0e73.firebasestorage.app',
  );
}
